services:
  # MySQL
  db:
    container_name: mysql8
    image: infobarbosa/mysql:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: ecommerce
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PWD: ""
    ports:
      - '33306:3306'
    volumes:
      - './server/mysql/etc/my.cnf:/etc/my.cnf'
